### ISSUE TITLE
Vertical/horizontal settings ignored

### ISSUE THREAD

**Issue by admirabilis** [Christoph142/TextboxAutoResizer#8]
Hello, Christoph! Long time no see!

There's a bug that's been happening to me since version 1.1 in Opera 12, and now that I've decided to move on, I tried the version 2.1 in Chrome 36, and the bug persists!

No matter what I choose in the settings, horizontal fields are also resized. What I'd like is that this extension only resizes vertical textboxes.

Thank you so much for your attention!

**Comment by Christoph142** [comment]
Hey :)
I don't think that's a bug since there's no setting for it. Let's call it a feature request.
I'll see what I can do for you ;)
(I guess you are referring to multi-line textareas vs. single-line text-fields with "vertical" and "horizontal"...?)

**Comment by Christoph142** [comment]
Try version 2.2 and tell me if that's what you requested and if it works for you ;)

**Comment by admirabilis** [comment]
That's perfect, really great! Thank you!!!

**Comment by Christoph142** [comment]
You're welcome ;)
